node.name: elasticsearch04
cluster.name: single-node-cluster
discovery.type: single-node
network.host: 0.0.0.0
# Authentication
xpack.security.enabled: true

# TLS encryption
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.client_authentication: optional
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12
